include:
  - local: .gitlab/templates/common.template.yml
  - local: .gitlab/templates/deploy-base.template.yml

stages:
  - build
  - check
  - deploy

build:library:
  needs: []
  stage: build
  interruptible: true
  allow_failure: false
  before_script:
    - docker login --username $DOCKER_REGISTRY_USER --password $DOCKER_REGISTRY_PASS $DOCKER_REGISTRY
  script:
    - docker-compose --file docker-compose.yml build utilities_build
    - docker-compose --file docker-compose.yml push utilities_build

build:docs:
  needs: []
  stage: build
  interruptible: true
  allow_failure: true
  before_script:
    - docker login --username $DOCKER_REGISTRY_USER --password $DOCKER_REGISTRY_PASS $DOCKER_REGISTRY
  script:
    - docker-compose --file docker-compose.yml build utilities_docs

check:lint:
  needs: []
  stage: check
  interruptible: true
  allow_failure: false
  before_script:
    - docker login --username $DOCKER_REGISTRY_USER --password $DOCKER_REGISTRY_PASS $DOCKER_REGISTRY
  script:
    - docker-compose --file docker-compose.yml build utilities_lint

check:test:
  needs: []
  stage: check
  interruptible: true
  allow_failure: false
  before_script:
    - docker login --username $DOCKER_REGISTRY_USER --password $DOCKER_REGISTRY_PASS $DOCKER_REGISTRY
  script:
    - docker-compose --file docker-compose.yml build utilities_test

deploy:next:
  extends: .deploy-base
  stage: deploy
  interruptible: false
  allow_failure: true
  when: manual
  variables:
    PUBLISH: 'true'
    PKG_VERSION: ${CI_COMMIT_SHORT_SHA}
    PKG_TAG: 'next'

deploy:stable:
  extends: .deploy-base
  stage: deploy
  interruptible: false
  allow_failure: true
  when: manual
  only:
    - master
  variables:
    PUBLISH: 'true'
    PKG_VERSION: ${CI_COMMIT_SHORT_SHA}
    PKG_TAG: 'stable'
