variables:
  NPM_AUTH_TOKEN: ${CI_JOB_TOKEN}
  GIT_COMMIT_HASH: ${CI_COMMIT_SHORT_SHA}

default:
  tags:
    - docker-executor
  image:
    name: dockerhub.bimeister.io/proxy_cache/library/node:16-slim
    entrypoint: ['']

stages:
  - preinstall
  - build
  - check
  - deploy

Dependencies:
  stage: preinstall
  needs: []
  interruptible: true
  allow_failure: false
  script:
    - npm install
    - npm run barrel
  cache:
    key: dependencies
    paths:
      - node_modules/
  artifacts:
    paths:
      - ./

Static Files:
  stage: build
  needs: ['Dependencies']
  dependencies:
    - 'Dependencies'
  interruptible: true
  allow_failure: false
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
      - node_modules/

Lint:
  stage: check
  needs: ['Dependencies']
  interruptible: true
  allow_failure: false
  script:
    - npm run lint

Spell Check:
  stage: check
  needs: ['Dependencies']
  interruptible: true
  allow_failure: false
  script:
    - npm run cspell:check

Test:
  stage: check
  needs: ['Dependencies']
  interruptible: true
  allow_failure: false
  script:
    - npm run test:ci
  artifacts:
    name: 'code-coverage'
    when: always
    reports:
      junit:
        - coverage/junit.xml

Code Style:
  stage: check
  needs: ['Dependencies']
  interruptible: true
  allow_failure: false
  script:
    - npm run prettier:check

NPM (dev):
  stage: deploy
  needs: ['Static Files']
  dependencies:
    - 'Static Files'
  interruptible: false
  allow_failure: true
  variables:
    TAG: 'dev'
  except:
    - master
  when: manual
  script:
    - node ./node_modules/@bimeister/build-cli/executable.js npm-package npmrc-prepare --npmrc_path="./.npmrc"
      --auth_token="${NPM_AUTH_TOKEN}" --org_email="info@bimeister.com"
      --registry="https://git.bimeister.io/api/v4/projects/98/packages/npm/" --remove_scoped_registries="true"
    - cp ./.npmrc ./.npmignore ./LICENSE --target-directory ./dist/
    - node ./node_modules/@bimeister/build-cli/executable.js npm-package package-json-prepare
      --package_json_path="./dist/package.json" --commit_hash="${GIT_COMMIT_HASH}-dev"
    - npm publish ./dist/ --tag="${TAG}" --access="public"

NPM (stable):
  stage: deploy
  needs: ['Static Files', 'Test', 'Code Style', 'Lint', 'Spell Check']
  dependencies:
    - 'Static Files'
  interruptible: false
  allow_failure: true
  variables:
    TAG: 'stable'
  only:
    - master
  when: always
  script:
    - node ./node_modules/@bimeister/build-cli/executable.js npm-package npmrc-prepare --npmrc_path="./.npmrc"
      --auth_token="${NPM_AUTH_TOKEN}" --org_email="info@bimeister.com"
      --registry="https://git.bimeister.io/api/v4/projects/98/packages/npm/" --remove_scoped_registries="true"
    - cp ./.npmrc ./.npmignore ./LICENSE --target-directory ./dist/
    - node ./node_modules/@bimeister/build-cli/executable.js npm-package package-json-prepare
      --package_json_path="./dist/package.json" --commit_hash="${GIT_COMMIT_HASH}"
    - npm publish ./dist/ --tag="${TAG}" --access="public"
