include:
  - local: .gitlab/templates/common.template.yml

stages:
  - preinstall
  - build
  - check
  - deploy

Dependencies:
  stage: preinstall
  needs: []
  interruptible: true
  allow_failure: false
  script:
    - scripts/build.sh base_service

Static files:
  stage: build
  needs: ['Dependencies']
  interruptible: true
  allow_failure: false
  script:
    - scripts/build.sh build_service

Docs:
  stage: build
  needs: ['Dependencies']
  interruptible: true
  allow_failure: false
  when: always
  only:
    - master
  variables:
    CI: 'true'
  script:
    - scripts/build.sh docs_service

Lint:
  stage: check
  needs: ['Dependencies']
  interruptible: true
  allow_failure: false
  script:
    - scripts/build.sh lint_service

Test:
  stage: check
  needs: ['Dependencies']
  interruptible: true
  allow_failure: false
  script:
    - scripts/build.sh test_service

NPM Package:
  stage: deploy
  needs: ['Static files', 'Test', 'Lint']
  interruptible: false
  allow_failure: true
  when: manual
  script:
    - scripts/build.sh deploy_service

pages:
  stage: deploy
  needs: ['Docs']
  interruptible: true
  allow_failure: true
  variables:
    CI: 'true'
  script:
    - scripts/build.sh utilities_docs
    - scripts/cp-from-image.sh "${DEFAULT_LABELS};service=utilities_docs" docs public
  when: always
  only:
    - master
  artifacts:
    when: always
    paths:
      - public
