FROM node:14.5-slim as utilities-lint

# NPM dependencies preinstall
WORKDIR /tmp
COPY .npmrc package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts --ignore-optional \
  && mkdir --parents /lint \
  && cp --archive /tmp/node_modules /lint

# lint library sources
WORKDIR /lint
COPY . .
RUN yarn run lint:inspect \
 && yarn run prettier:check
