FROM node:14.5-slim as utilities-docs

# NPM dependencies preinstall
WORKDIR /tmp
COPY .npmrc package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts --ignore-optional \
  && mkdir --parents /docs \
  && cp --archive /tmp/node_modules /docs

# Generate docs html representation
WORKDIR /docs
COPY . .
RUN yarn run build:docs
