version: '3.4'

services:
  base_service:
    build:
      context: ./
      dockerfile: ./build/docker/multistage.dockerfile
      target: base
      args:
        - NPM_AUTH_TOKEN

  build_service:
    build:
      context: ./
      dockerfile: ./build/docker/multistage.dockerfile
      target: build
      args:
        - NPM_AUTH_TOKEN

  lint_service:
    build:
      context: ./
      dockerfile: ./build/docker/multistage.dockerfile
      target: lint
      args:
        - NPM_AUTH_TOKEN

  test_service:
    build:
      context: ./
      dockerfile: ./build/docker/multistage.dockerfile
      target: test
      args:
        - NPM_AUTH_TOKEN

  deploy_service:
    build:
      context: ./
      dockerfile: ./build/docker/multistage.dockerfile
      target: deploy
      args:
        - NPM_AUTH_TOKEN
        - GIT_COMMIT_HASH

  docs_service:
    build:
      context: ./
      dockerfile: ./build/docker/multistage.dockerfile
      target: docs
      labels:
        meistersoft.build.pipeline: ${CI_PIPELINE_IID}
        meistersoft.git.commit: ${GIT_COMMIT}
        meistersoft.git.branch: ${BRANCH_NAME}
        service: docs_service
