version: '3.4'

services:
  base_service:
    build:
      context: ./
      dockerfile: ./build/docker/base.dockerfile
    image: ${BASE_IMAGE}

  build_service:
    build:
      context: ./
      dockerfile: ./build/docker/build.dockerfile
      args:
        - BASE_IMAGE
    image: ${BUILD_IMAGE}

  lint_service:
    build:
      context: ./
      dockerfile: ./build/docker/lint.dockerfile
      args:
        - BASE_IMAGE

  codestyle_service:
    build:
      context: ./
      dockerfile: ./build/docker/codestyle.dockerfile
      args:
        - BASE_IMAGE

  test_service:
    build:
      context: ./
      dockerfile: ./build/docker/test.dockerfile
      args:
        - BASE_IMAGE
      labels:
        pipeline: ${PIPELINE_ID}
        commit: ${GIT_COMMIT_HASH}
        service: test_service

  deploy_service:
    build:
      context: ./
      dockerfile: ./build/docker/deploy.dockerfile
      args:
        - NPM_AUTH_TOKEN
        - GIT_COMMIT_HASH
        - BUILD_IMAGE
        - TAG

  docs_service:
    build:
      context: ./
      dockerfile: ./build/docker/docs.dockerfile
      labels:
        pipeline: ${PIPELINE_ID}
        commit: ${GIT_COMMIT_HASH}
        service: docs_service
      args:
        - BASE_IMAGE
