version: '3.4'

services:
  utilities_build:
    image: ${BUILD_IMAGE}
    build:
      context: ./
      dockerfile: Dockerfile.build
    environment:
      - PKG_VERSION
      - PKG_TAG
      - PUBLISH
      - NPM_REPOSITORY_LOGIN
      - NPM_REPOSITORY_PASSWORD
      - NPM_REPOSITORY_EMAIL
      - NPM_REPOSITORY_URL

  utilities_lint:
    build:
      context: ./
      dockerfile: Dockerfile.lint

  utilities_test:
    build:
      context: ./
      dockerfile: Dockerfile.test

  utilities_docs:
    image: ${DOCS_IMAGE}
    build:
      context: ./
      dockerfile: Dockerfile.docs
    labels:
      tag: ${DOCS_IMAGE_TAG}
