FROM node:14.5-slim as utilities-build
RUN apt update && apt-get install jq -y

# NPM dependencies preinstall
WORKDIR /tmp
COPY .npmrc package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts \
  && mkdir --parents /utilities \
  && cp --archive /tmp/node_modules /utilities

# build library sources
WORKDIR /utilities
COPY . .
RUN yarn run build:ci

ENTRYPOINT ["local-scripts/publish.sh"]
