FROM node:14.5-slim as utilities-docs

# NPM dependencies preinstall
WORKDIR /tmp
COPY .npmrc package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts \
  && mkdir --parents /utilities \
  && cp --archive /tmp/node_modules /utilities

# Generate docs html representation
WORKDIR /utilities
COPY . .
RUN yarn run build:docs
