FROM node:14.5-slim as utilities-build
RUN apt update && apt-get install jq -y

# NPM dependencies preinstall
WORKDIR /tmp
COPY .npmrc package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts --ignore-optional \
  && mkdir --parents /build \
  && cp --archive /tmp/node_modules /build

# build library sources
WORKDIR /build
COPY . .
RUN yarn run build:ci

ENTRYPOINT ["scripts/publish.sh"]
