FROM node:14.5-slim as utilities-lint

# NPM dependencies preinstall
WORKDIR /tmp
COPY .npmrc package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts \
  && mkdir --parents /utilities \
  && cp --archive /tmp/node_modules /utilities

# lint library sources
WORKDIR /utilities
COPY . .
RUN yarn run lint:inspect \
 && yarn run prettier:check
