version: '3.4'

services:
  utilities_build:
    build:
      context: ./
      dockerfile: Dockerfile.build
    environment:
      - PKG_VERSION
      - PKG_TAG
      - PUBLISH
      - NPM_REPOSITORY_LOGIN
      - NPM_REPOSITORY_PASSWORD
      - NPM_REPOSITORY_EMAIL
      - NPM_REPOSITORY_URL

  utilities_lint:
    build:
      context: ./
      dockerfile: Dockerfile.lint

  utilities_test:
    build:
      context: ./
      dockerfile: Dockerfile.test

  utilities_docs:
    build:
      context: ./
      dockerfile: Dockerfile.docs
      labels:
        meistersoft.build.pipeline: ${CI_PIPELINE_IID}
        meistersoft.git.commit: ${GIT_COMMIT}
        meistersoft.git.branch: ${BRANCH_NAME}
        service: utilities_docs
