/**
 * @file Automatically generated by barrelsby.
 */

export * from './resize-observer-entry.interface';
export * from './resize-observer-options.interface';
export * from './resize-observer.interface';
