import type { Config } from 'jest';

const transpilingOptions: Config = {
  transform: {
    '^.+\\.(ts|mjs|html|svg)$': [
      'ts-jest',
      {
        tsconfig: '<rootDir>/../tsconfig.test.json',
        stringifyContentPathRegex: '\\.(html|svg)$',
      },
    ],
  },
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
};

const baseConfig: Config = {
  ...transpilingOptions,
  coverageThreshold: {
    global: {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
  },
  rootDir: '../',
  coverageDirectory: '<rootDir>/coverage',
  testMatch: ['*.spec.ts'],
  moduleFileExtensions: ['ts', 'js'],
  projects: [
    {
      ...transpilingOptions,
      displayName: 'common',
      testMatch: ['<rootDir>/common/src/**/*.spec.ts'],
    },
    {
      ...transpilingOptions,
      displayName: 'intersection-observable',
      testMatch: ['<rootDir>/intersection-observable/src/**/*.spec.ts'],
    },
    {
      ...transpilingOptions,
      displayName: 'resize-observable',
      testMatch: ['<rootDir>/resize-observable/src/**/*.spec.ts'],
    },
    {
      ...transpilingOptions,
      displayName: 'rxjs',
      testMatch: ['<rootDir>/rxjs/src/**/*.spec.ts'],
    },
    {
      ...transpilingOptions,
      displayName: 'filesystem',
      testMatch: ['<rootDir>/filesystem/src/**/*.spec.ts'],
    },
  ],
  verbose: true,
  collectCoverageFrom: [
    '**/*.ts', // all TypeScript files
    '!**/*.enum.ts', // except non-testable files
    '!**/*.const.ts', // except non-testable files
    '!**/*.interface.ts', // except non-testable files
    '!**/*.type.ts', // except non-testable files
    '!jest.config-base.ts', // except config files
    '!jest.config-pipeline.ts', // except config files
    '!jest.config.ts', // except config files
    '!**/*.spec.ts', // except test files
    '!**/index.ts', // except autogenerated files
    '!**/api.ts', // except autogenerated files
    '!**/build/**/*.ts', // except build utilities
    '!**/traits/**/*.ts', // except traits files
    '!**/performance/**/*.ts', // except performance files
    '!**/index/**/*.ts', // except index files
  ],
};

export default baseConfig;
