name: Release Package

on:
  push:
    branches:
      - 'main'

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies by lockfile
        run: npm clean-install

      - name: Generate Public API
        run: npm run barrel

      - name: Pack prepared workspace to archive
        run: tar --totals --create --file workspace.tar ./

      - name: Share prepared workspace with other jobs
        uses: actions/cache@v3
        with:
          key: "workspace:${{github.sha}}"
          path: workspace.tar

  static_files:
    name: Build Static Files
    runs-on: ubuntu-latest
    needs: [ install_dependencies ]
    steps:
      - name: Download prepared workspace
        uses: actions/cache@v3
        with:
          key: "workspace:${{github.sha}}"
          path: workspace.tar

      - name: Restore workspace from archive
        run: tar --totals --extract --file workspace.tar && rm --force workspace.tar

      - name: Build static files
        run: npm run build

      - name: Pack static files to archive
        run: tar --totals --create --file dist.tar ./

      - name: Share prepared workspace with other jobs
        uses: actions/cache@v3
        with:
          key: "dist:${{github.sha}}"
          path: dist.tar

  publish:
    name: Run publish
    runs-on: ubuntu-latest
    needs: [ static_files ]
    steps:
      - name: Download prepared dist
        uses: actions/cache@v3
        with:
          key: "dist:${{github.sha}}"
          path: dist.tar

      - name: Restore dist from archive
        run: tar --totals --extract --file dist.tar && rm --force dist.tar

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 18

      - name: 'Authorize to NPM Registry'
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_DEPLOY_TOKEN}}" >> dist/.npmrc

      - name: Do prepublish
        run: npm run build:prepublish
        env:
          GIT_COMMIT_HASH: ${{github.sha}}
      
      - name: Logs
        run: cat dist/.npmrc
        
      - name: Publish
        run: cd dist && npm publish --access public
